DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS usuario;
 
CREATE TABLE person(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  age NUMERIC NOT NULL,
  salary NUMERIC NOT NULL
);

CREATE TABLE usuario(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  rol VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
);
