DROP TABLE IF EXISTS role_endpoints;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS person;

CREATE TABLE person(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  age NUMERIC NOT NULL,
  salary NUMERIC NOT NULL
);

CREATE TABLE roles(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE users(
  id NUMERIC IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  rol_id NUMERIC NOT NULL,
  password VARCHAR NOT NULL,
  FOREIGN KEY (rol_id) REFERENCES roles(id)
);

CREATE TABLE role_endpoints(
  id NUMERIC IDENTITY PRIMARY KEY,
  role_id NUMERIC NOT NULL,
  endpoint VARCHAR NOT NULL,
  accion VARCHAR NOT NULL,
  FOREIGN KEY (role_id) REFERENCES roles(id),
  CONSTRAINT UQ_ROLE_ENDPOINT UNIQUE (role_id, endpoint)
);
